// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTypechoMetas = "typecho_metas"

// TypechoMetas mapped from table <typecho_metas>
type TypechoMetas struct {
	Mid         uint32  `gorm:"column:mid;type:int(10) unsigned;primaryKey;autoIncrement:true" json:"mid"`
	Name        *string `gorm:"column:name;type:varchar(150)" json:"name"`
	Slug        *string `gorm:"column:slug;type:varchar(150);index:slug,priority:1" json:"slug"`
	Type        string  `gorm:"column:type;type:varchar(32);not null" json:"type"`
	Description *string `gorm:"column:description;type:varchar(150)" json:"description"`
	Count_      *uint32 `gorm:"column:count;type:int(10) unsigned" json:"count"`
	Order_      *uint32 `gorm:"column:order;type:int(10) unsigned" json:"order"`
	Parent      *uint32 `gorm:"column:parent;type:int(10) unsigned" json:"parent"`
}

// TableName TypechoMetas's table name
func (*TypechoMetas) TableName() string {
	return TableNameTypechoMetas
}
