/*
Halo

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.20.18
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package console_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SettingRef type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SettingRef{}

// SettingRef struct for SettingRef
type SettingRef struct {
	Group string `json:"group"`
	Name string `json:"name"`
}

type _SettingRef SettingRef

// NewSettingRef instantiates a new SettingRef object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSettingRef(group string, name string) *SettingRef {
	this := SettingRef{}
	this.Group = group
	this.Name = name
	return &this
}

// NewSettingRefWithDefaults instantiates a new SettingRef object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSettingRefWithDefaults() *SettingRef {
	this := SettingRef{}
	return &this
}

// GetGroup returns the Group field value
func (o *SettingRef) GetGroup() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Group
}

// GetGroupOk returns a tuple with the Group field value
// and a boolean to check if the value has been set.
func (o *SettingRef) GetGroupOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Group, true
}

// SetGroup sets field value
func (o *SettingRef) SetGroup(v string) {
	o.Group = v
}

// GetName returns the Name field value
func (o *SettingRef) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SettingRef) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SettingRef) SetName(v string) {
	o.Name = v
}

func (o SettingRef) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SettingRef) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["group"] = o.Group
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *SettingRef) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"group",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSettingRef := _SettingRef{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSettingRef)

	if err != nil {
		return err
	}

	*o = SettingRef(varSettingRef)

	return err
}

type NullableSettingRef struct {
	value *SettingRef
	isSet bool
}

func (v NullableSettingRef) Get() *SettingRef {
	return v.value
}

func (v *NullableSettingRef) Set(val *SettingRef) {
	v.value = val
	v.isSet = true
}

func (v NullableSettingRef) IsSet() bool {
	return v.isSet
}

func (v *NullableSettingRef) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSettingRef(val *SettingRef) *NullableSettingRef {
	return &NullableSettingRef{value: val, isSet: true}
}

func (v NullableSettingRef) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSettingRef) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


