/*
Halo

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.20.18
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package console_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RevertSnapshotForSingleParam type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RevertSnapshotForSingleParam{}

// RevertSnapshotForSingleParam struct for RevertSnapshotForSingleParam
type RevertSnapshotForSingleParam struct {
	SnapshotName string `json:"snapshotName"`
}

type _RevertSnapshotForSingleParam RevertSnapshotForSingleParam

// NewRevertSnapshotForSingleParam instantiates a new RevertSnapshotForSingleParam object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRevertSnapshotForSingleParam(snapshotName string) *RevertSnapshotForSingleParam {
	this := RevertSnapshotForSingleParam{}
	this.SnapshotName = snapshotName
	return &this
}

// NewRevertSnapshotForSingleParamWithDefaults instantiates a new RevertSnapshotForSingleParam object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRevertSnapshotForSingleParamWithDefaults() *RevertSnapshotForSingleParam {
	this := RevertSnapshotForSingleParam{}
	return &this
}

// GetSnapshotName returns the SnapshotName field value
func (o *RevertSnapshotForSingleParam) GetSnapshotName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SnapshotName
}

// GetSnapshotNameOk returns a tuple with the SnapshotName field value
// and a boolean to check if the value has been set.
func (o *RevertSnapshotForSingleParam) GetSnapshotNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SnapshotName, true
}

// SetSnapshotName sets field value
func (o *RevertSnapshotForSingleParam) SetSnapshotName(v string) {
	o.SnapshotName = v
}

func (o RevertSnapshotForSingleParam) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RevertSnapshotForSingleParam) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["snapshotName"] = o.SnapshotName
	return toSerialize, nil
}

func (o *RevertSnapshotForSingleParam) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"snapshotName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRevertSnapshotForSingleParam := _RevertSnapshotForSingleParam{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRevertSnapshotForSingleParam)

	if err != nil {
		return err
	}

	*o = RevertSnapshotForSingleParam(varRevertSnapshotForSingleParam)

	return err
}

type NullableRevertSnapshotForSingleParam struct {
	value *RevertSnapshotForSingleParam
	isSet bool
}

func (v NullableRevertSnapshotForSingleParam) Get() *RevertSnapshotForSingleParam {
	return v.value
}

func (v *NullableRevertSnapshotForSingleParam) Set(val *RevertSnapshotForSingleParam) {
	v.value = val
	v.isSet = true
}

func (v NullableRevertSnapshotForSingleParam) IsSet() bool {
	return v.isSet
}

func (v *NullableRevertSnapshotForSingleParam) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRevertSnapshotForSingleParam(val *RevertSnapshotForSingleParam) *NullableRevertSnapshotForSingleParam {
	return &NullableRevertSnapshotForSingleParam{value: val, isSet: true}
}

func (v NullableRevertSnapshotForSingleParam) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRevertSnapshotForSingleParam) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


