/*
Halo

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.20.18
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package console_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConfigMapRef type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigMapRef{}

// ConfigMapRef struct for ConfigMapRef
type ConfigMapRef struct {
	Name string `json:"name"`
}

type _ConfigMapRef ConfigMapRef

// NewConfigMapRef instantiates a new ConfigMapRef object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigMapRef(name string) *ConfigMapRef {
	this := ConfigMapRef{}
	this.Name = name
	return &this
}

// NewConfigMapRefWithDefaults instantiates a new ConfigMapRef object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigMapRefWithDefaults() *ConfigMapRef {
	this := ConfigMapRef{}
	return &this
}

// GetName returns the Name field value
func (o *ConfigMapRef) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ConfigMapRef) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ConfigMapRef) SetName(v string) {
	o.Name = v
}

func (o ConfigMapRef) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigMapRef) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *ConfigMapRef) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigMapRef := _ConfigMapRef{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConfigMapRef)

	if err != nil {
		return err
	}

	*o = ConfigMapRef(varConfigMapRef)

	return err
}

type NullableConfigMapRef struct {
	value *ConfigMapRef
	isSet bool
}

func (v NullableConfigMapRef) Get() *ConfigMapRef {
	return v.value
}

func (v *NullableConfigMapRef) Set(val *ConfigMapRef) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigMapRef) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigMapRef) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigMapRef(val *ConfigMapRef) *NullableConfigMapRef {
	return &NullableConfigMapRef{value: val, isSet: true}
}

func (v NullableConfigMapRef) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigMapRef) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


