/*
Halo

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.20.18
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package console_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListedReplyList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListedReplyList{}

// ListedReplyList struct for ListedReplyList
type ListedReplyList struct {
	// Indicates whether current page is the first page.
	First bool `json:"first"`
	// Indicates whether current page has previous page.
	HasNext bool `json:"hasNext"`
	// Indicates whether current page has previous page.
	HasPrevious bool `json:"hasPrevious"`
	// A chunk of items.
	Items []ListedReply `json:"items"`
	// Indicates whether current page is the last page.
	Last bool `json:"last"`
	// Page number, starts from 1. If not set or equal to 0, it means no pagination.
	Page int32 `json:"page"`
	// Size of each page. If not set or equal to 0, it means no pagination.
	Size int32 `json:"size"`
	// Total elements.
	Total int64 `json:"total"`
	// Indicates total pages.
	TotalPages int64 `json:"totalPages"`
}

type _ListedReplyList ListedReplyList

// NewListedReplyList instantiates a new ListedReplyList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListedReplyList(first bool, hasNext bool, hasPrevious bool, items []ListedReply, last bool, page int32, size int32, total int64, totalPages int64) *ListedReplyList {
	this := ListedReplyList{}
	this.First = first
	this.HasNext = hasNext
	this.HasPrevious = hasPrevious
	this.Items = items
	this.Last = last
	this.Page = page
	this.Size = size
	this.Total = total
	this.TotalPages = totalPages
	return &this
}

// NewListedReplyListWithDefaults instantiates a new ListedReplyList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListedReplyListWithDefaults() *ListedReplyList {
	this := ListedReplyList{}
	return &this
}

// GetFirst returns the First field value
func (o *ListedReplyList) GetFirst() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.First
}

// GetFirstOk returns a tuple with the First field value
// and a boolean to check if the value has been set.
func (o *ListedReplyList) GetFirstOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.First, true
}

// SetFirst sets field value
func (o *ListedReplyList) SetFirst(v bool) {
	o.First = v
}

// GetHasNext returns the HasNext field value
func (o *ListedReplyList) GetHasNext() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasNext
}

// GetHasNextOk returns a tuple with the HasNext field value
// and a boolean to check if the value has been set.
func (o *ListedReplyList) GetHasNextOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasNext, true
}

// SetHasNext sets field value
func (o *ListedReplyList) SetHasNext(v bool) {
	o.HasNext = v
}

// GetHasPrevious returns the HasPrevious field value
func (o *ListedReplyList) GetHasPrevious() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasPrevious
}

// GetHasPreviousOk returns a tuple with the HasPrevious field value
// and a boolean to check if the value has been set.
func (o *ListedReplyList) GetHasPreviousOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasPrevious, true
}

// SetHasPrevious sets field value
func (o *ListedReplyList) SetHasPrevious(v bool) {
	o.HasPrevious = v
}

// GetItems returns the Items field value
func (o *ListedReplyList) GetItems() []ListedReply {
	if o == nil {
		var ret []ListedReply
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ListedReplyList) GetItemsOk() ([]ListedReply, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ListedReplyList) SetItems(v []ListedReply) {
	o.Items = v
}

// GetLast returns the Last field value
func (o *ListedReplyList) GetLast() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Last
}

// GetLastOk returns a tuple with the Last field value
// and a boolean to check if the value has been set.
func (o *ListedReplyList) GetLastOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Last, true
}

// SetLast sets field value
func (o *ListedReplyList) SetLast(v bool) {
	o.Last = v
}

// GetPage returns the Page field value
func (o *ListedReplyList) GetPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *ListedReplyList) GetPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *ListedReplyList) SetPage(v int32) {
	o.Page = v
}

// GetSize returns the Size field value
func (o *ListedReplyList) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *ListedReplyList) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *ListedReplyList) SetSize(v int32) {
	o.Size = v
}

// GetTotal returns the Total field value
func (o *ListedReplyList) GetTotal() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *ListedReplyList) GetTotalOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *ListedReplyList) SetTotal(v int64) {
	o.Total = v
}

// GetTotalPages returns the TotalPages field value
func (o *ListedReplyList) GetTotalPages() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TotalPages
}

// GetTotalPagesOk returns a tuple with the TotalPages field value
// and a boolean to check if the value has been set.
func (o *ListedReplyList) GetTotalPagesOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalPages, true
}

// SetTotalPages sets field value
func (o *ListedReplyList) SetTotalPages(v int64) {
	o.TotalPages = v
}

func (o ListedReplyList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListedReplyList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["first"] = o.First
	toSerialize["hasNext"] = o.HasNext
	toSerialize["hasPrevious"] = o.HasPrevious
	toSerialize["items"] = o.Items
	toSerialize["last"] = o.Last
	toSerialize["page"] = o.Page
	toSerialize["size"] = o.Size
	toSerialize["total"] = o.Total
	toSerialize["totalPages"] = o.TotalPages
	return toSerialize, nil
}

func (o *ListedReplyList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"first",
		"hasNext",
		"hasPrevious",
		"items",
		"last",
		"page",
		"size",
		"total",
		"totalPages",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListedReplyList := _ListedReplyList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListedReplyList)

	if err != nil {
		return err
	}

	*o = ListedReplyList(varListedReplyList)

	return err
}

type NullableListedReplyList struct {
	value *ListedReplyList
	isSet bool
}

func (v NullableListedReplyList) Get() *ListedReplyList {
	return v.value
}

func (v *NullableListedReplyList) Set(val *ListedReplyList) {
	v.value = val
	v.isSet = true
}

func (v NullableListedReplyList) IsSet() bool {
	return v.isSet
}

func (v *NullableListedReplyList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListedReplyList(val *ListedReplyList) *NullableListedReplyList {
	return &NullableListedReplyList{value: val, isSet: true}
}

func (v NullableListedReplyList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListedReplyList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


