/*
Halo

Testing SystemConfigV1alpha1ConsoleAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package console_sdk

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "api.halo.run/apis/openapi-go-console"
)

func Test_console_sdk_SystemConfigV1alpha1ConsoleAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SystemConfigV1alpha1ConsoleAPIService GetSystemConfigByGroup", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var group string

		resp, httpRes, err := apiClient.SystemConfigV1alpha1ConsoleAPI.GetSystemConfigByGroup(context.Background(), group).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SystemConfigV1alpha1ConsoleAPIService UpdateSystemConfigByGroup", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var group string

		httpRes, err := apiClient.SystemConfigV1alpha1ConsoleAPI.UpdateSystemConfigByGroup(context.Background(), group).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
