/*
Halo

Testing SnapshotV1alpha1UcAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package user_sdk

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "api.halo.run/apis/openapi-go-user"
)

func Test_user_sdk_SnapshotV1alpha1UcAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SnapshotV1alpha1UcAPIService GetSnapshotForPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var name string

		resp, httpRes, err := apiClient.SnapshotV1alpha1UcAPI.GetSnapshotForPost(context.Background(), name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
