/*
Halo

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.20.18
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package extension_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ExtensionSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExtensionSpec{}

// ExtensionSpec struct for ExtensionSpec
type ExtensionSpec struct {
	ClassName string `json:"className"`
	Description *string `json:"description,omitempty"`
	DisplayName string `json:"displayName"`
	ExtensionPointName string `json:"extensionPointName"`
	Icon *string `json:"icon,omitempty"`
}

type _ExtensionSpec ExtensionSpec

// NewExtensionSpec instantiates a new ExtensionSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExtensionSpec(className string, displayName string, extensionPointName string) *ExtensionSpec {
	this := ExtensionSpec{}
	this.ClassName = className
	this.DisplayName = displayName
	this.ExtensionPointName = extensionPointName
	return &this
}

// NewExtensionSpecWithDefaults instantiates a new ExtensionSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExtensionSpecWithDefaults() *ExtensionSpec {
	this := ExtensionSpec{}
	return &this
}

// GetClassName returns the ClassName field value
func (o *ExtensionSpec) GetClassName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClassName
}

// GetClassNameOk returns a tuple with the ClassName field value
// and a boolean to check if the value has been set.
func (o *ExtensionSpec) GetClassNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClassName, true
}

// SetClassName sets field value
func (o *ExtensionSpec) SetClassName(v string) {
	o.ClassName = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ExtensionSpec) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExtensionSpec) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ExtensionSpec) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ExtensionSpec) SetDescription(v string) {
	o.Description = &v
}

// GetDisplayName returns the DisplayName field value
func (o *ExtensionSpec) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *ExtensionSpec) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *ExtensionSpec) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetExtensionPointName returns the ExtensionPointName field value
func (o *ExtensionSpec) GetExtensionPointName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExtensionPointName
}

// GetExtensionPointNameOk returns a tuple with the ExtensionPointName field value
// and a boolean to check if the value has been set.
func (o *ExtensionSpec) GetExtensionPointNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExtensionPointName, true
}

// SetExtensionPointName sets field value
func (o *ExtensionSpec) SetExtensionPointName(v string) {
	o.ExtensionPointName = v
}

// GetIcon returns the Icon field value if set, zero value otherwise.
func (o *ExtensionSpec) GetIcon() string {
	if o == nil || IsNil(o.Icon) {
		var ret string
		return ret
	}
	return *o.Icon
}

// GetIconOk returns a tuple with the Icon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExtensionSpec) GetIconOk() (*string, bool) {
	if o == nil || IsNil(o.Icon) {
		return nil, false
	}
	return o.Icon, true
}

// HasIcon returns a boolean if a field has been set.
func (o *ExtensionSpec) HasIcon() bool {
	if o != nil && !IsNil(o.Icon) {
		return true
	}

	return false
}

// SetIcon gets a reference to the given string and assigns it to the Icon field.
func (o *ExtensionSpec) SetIcon(v string) {
	o.Icon = &v
}

func (o ExtensionSpec) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExtensionSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["className"] = o.ClassName
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["displayName"] = o.DisplayName
	toSerialize["extensionPointName"] = o.ExtensionPointName
	if !IsNil(o.Icon) {
		toSerialize["icon"] = o.Icon
	}
	return toSerialize, nil
}

func (o *ExtensionSpec) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"className",
		"displayName",
		"extensionPointName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExtensionSpec := _ExtensionSpec{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExtensionSpec)

	if err != nil {
		return err
	}

	*o = ExtensionSpec(varExtensionSpec)

	return err
}

type NullableExtensionSpec struct {
	value *ExtensionSpec
	isSet bool
}

func (v NullableExtensionSpec) Get() *ExtensionSpec {
	return v.value
}

func (v *NullableExtensionSpec) Set(val *ExtensionSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableExtensionSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableExtensionSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExtensionSpec(val *ExtensionSpec) *NullableExtensionSpec {
	return &NullableExtensionSpec{value: val, isSet: true}
}

func (v NullableExtensionSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExtensionSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


