/*
Halo

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.20.18
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package extension_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ExtensionPointDefinitionList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExtensionPointDefinitionList{}

// ExtensionPointDefinitionList struct for ExtensionPointDefinitionList
type ExtensionPointDefinitionList struct {
	// Indicates whether current page is the first page.
	First bool `json:"first"`
	// Indicates whether current page has previous page.
	HasNext bool `json:"hasNext"`
	// Indicates whether current page has previous page.
	HasPrevious bool `json:"hasPrevious"`
	// A chunk of items.
	Items []ExtensionPointDefinition `json:"items"`
	// Indicates whether current page is the last page.
	Last bool `json:"last"`
	// Page number, starts from 1. If not set or equal to 0, it means no pagination.
	Page int32 `json:"page"`
	// Size of each page. If not set or equal to 0, it means no pagination.
	Size int32 `json:"size"`
	// Total elements.
	Total int64 `json:"total"`
	// Indicates total pages.
	TotalPages int64 `json:"totalPages"`
}

type _ExtensionPointDefinitionList ExtensionPointDefinitionList

// NewExtensionPointDefinitionList instantiates a new ExtensionPointDefinitionList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExtensionPointDefinitionList(first bool, hasNext bool, hasPrevious bool, items []ExtensionPointDefinition, last bool, page int32, size int32, total int64, totalPages int64) *ExtensionPointDefinitionList {
	this := ExtensionPointDefinitionList{}
	this.First = first
	this.HasNext = hasNext
	this.HasPrevious = hasPrevious
	this.Items = items
	this.Last = last
	this.Page = page
	this.Size = size
	this.Total = total
	this.TotalPages = totalPages
	return &this
}

// NewExtensionPointDefinitionListWithDefaults instantiates a new ExtensionPointDefinitionList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExtensionPointDefinitionListWithDefaults() *ExtensionPointDefinitionList {
	this := ExtensionPointDefinitionList{}
	return &this
}

// GetFirst returns the First field value
func (o *ExtensionPointDefinitionList) GetFirst() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.First
}

// GetFirstOk returns a tuple with the First field value
// and a boolean to check if the value has been set.
func (o *ExtensionPointDefinitionList) GetFirstOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.First, true
}

// SetFirst sets field value
func (o *ExtensionPointDefinitionList) SetFirst(v bool) {
	o.First = v
}

// GetHasNext returns the HasNext field value
func (o *ExtensionPointDefinitionList) GetHasNext() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasNext
}

// GetHasNextOk returns a tuple with the HasNext field value
// and a boolean to check if the value has been set.
func (o *ExtensionPointDefinitionList) GetHasNextOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasNext, true
}

// SetHasNext sets field value
func (o *ExtensionPointDefinitionList) SetHasNext(v bool) {
	o.HasNext = v
}

// GetHasPrevious returns the HasPrevious field value
func (o *ExtensionPointDefinitionList) GetHasPrevious() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasPrevious
}

// GetHasPreviousOk returns a tuple with the HasPrevious field value
// and a boolean to check if the value has been set.
func (o *ExtensionPointDefinitionList) GetHasPreviousOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasPrevious, true
}

// SetHasPrevious sets field value
func (o *ExtensionPointDefinitionList) SetHasPrevious(v bool) {
	o.HasPrevious = v
}

// GetItems returns the Items field value
func (o *ExtensionPointDefinitionList) GetItems() []ExtensionPointDefinition {
	if o == nil {
		var ret []ExtensionPointDefinition
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ExtensionPointDefinitionList) GetItemsOk() ([]ExtensionPointDefinition, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ExtensionPointDefinitionList) SetItems(v []ExtensionPointDefinition) {
	o.Items = v
}

// GetLast returns the Last field value
func (o *ExtensionPointDefinitionList) GetLast() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Last
}

// GetLastOk returns a tuple with the Last field value
// and a boolean to check if the value has been set.
func (o *ExtensionPointDefinitionList) GetLastOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Last, true
}

// SetLast sets field value
func (o *ExtensionPointDefinitionList) SetLast(v bool) {
	o.Last = v
}

// GetPage returns the Page field value
func (o *ExtensionPointDefinitionList) GetPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *ExtensionPointDefinitionList) GetPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *ExtensionPointDefinitionList) SetPage(v int32) {
	o.Page = v
}

// GetSize returns the Size field value
func (o *ExtensionPointDefinitionList) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *ExtensionPointDefinitionList) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *ExtensionPointDefinitionList) SetSize(v int32) {
	o.Size = v
}

// GetTotal returns the Total field value
func (o *ExtensionPointDefinitionList) GetTotal() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *ExtensionPointDefinitionList) GetTotalOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *ExtensionPointDefinitionList) SetTotal(v int64) {
	o.Total = v
}

// GetTotalPages returns the TotalPages field value
func (o *ExtensionPointDefinitionList) GetTotalPages() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TotalPages
}

// GetTotalPagesOk returns a tuple with the TotalPages field value
// and a boolean to check if the value has been set.
func (o *ExtensionPointDefinitionList) GetTotalPagesOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalPages, true
}

// SetTotalPages sets field value
func (o *ExtensionPointDefinitionList) SetTotalPages(v int64) {
	o.TotalPages = v
}

func (o ExtensionPointDefinitionList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExtensionPointDefinitionList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["first"] = o.First
	toSerialize["hasNext"] = o.HasNext
	toSerialize["hasPrevious"] = o.HasPrevious
	toSerialize["items"] = o.Items
	toSerialize["last"] = o.Last
	toSerialize["page"] = o.Page
	toSerialize["size"] = o.Size
	toSerialize["total"] = o.Total
	toSerialize["totalPages"] = o.TotalPages
	return toSerialize, nil
}

func (o *ExtensionPointDefinitionList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"first",
		"hasNext",
		"hasPrevious",
		"items",
		"last",
		"page",
		"size",
		"total",
		"totalPages",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExtensionPointDefinitionList := _ExtensionPointDefinitionList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExtensionPointDefinitionList)

	if err != nil {
		return err
	}

	*o = ExtensionPointDefinitionList(varExtensionPointDefinitionList)

	return err
}

type NullableExtensionPointDefinitionList struct {
	value *ExtensionPointDefinitionList
	isSet bool
}

func (v NullableExtensionPointDefinitionList) Get() *ExtensionPointDefinitionList {
	return v.value
}

func (v *NullableExtensionPointDefinitionList) Set(val *ExtensionPointDefinitionList) {
	v.value = val
	v.isSet = true
}

func (v NullableExtensionPointDefinitionList) IsSet() bool {
	return v.isSet
}

func (v *NullableExtensionPointDefinitionList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExtensionPointDefinitionList(val *ExtensionPointDefinitionList) *NullableExtensionPointDefinitionList {
	return &NullableExtensionPointDefinitionList{value: val, isSet: true}
}

func (v NullableExtensionPointDefinitionList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExtensionPointDefinitionList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


