/*
Halo

Testing MenuV1alpha1PublicAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package public_sdk

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "api.halo.run/apis/openapi-go-public"
)

func Test_public_sdk_MenuV1alpha1PublicAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test MenuV1alpha1PublicAPIService QueryMenuByName", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var name string

		resp, httpRes, err := apiClient.MenuV1alpha1PublicAPI.QueryMenuByName(context.Background(), name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MenuV1alpha1PublicAPIService QueryPrimaryMenu", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.MenuV1alpha1PublicAPI.QueryPrimaryMenu(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
