/*
Halo

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.20.18
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package public_sdk

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type MenuV1alpha1PublicAPI interface {

	/*
	QueryMenuByName Method for QueryMenuByName

	Gets menu by name.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param name Menu name
	@return ApiQueryMenuByNameRequest
	*/
	QueryMenuByName(ctx context.Context, name string) ApiQueryMenuByNameRequest

	// QueryMenuByNameExecute executes the request
	//  @return MenuVo
	QueryMenuByNameExecute(r ApiQueryMenuByNameRequest) (*MenuVo, *http.Response, error)

	/*
	QueryPrimaryMenu Method for QueryPrimaryMenu

	Gets primary menu.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiQueryPrimaryMenuRequest
	*/
	QueryPrimaryMenu(ctx context.Context) ApiQueryPrimaryMenuRequest

	// QueryPrimaryMenuExecute executes the request
	//  @return MenuVo
	QueryPrimaryMenuExecute(r ApiQueryPrimaryMenuRequest) (*MenuVo, *http.Response, error)
}

// MenuV1alpha1PublicAPIService MenuV1alpha1PublicAPI service
type MenuV1alpha1PublicAPIService service

type ApiQueryMenuByNameRequest struct {
	ctx context.Context
	ApiService MenuV1alpha1PublicAPI
	name string
}

func (r ApiQueryMenuByNameRequest) Execute() (*MenuVo, *http.Response, error) {
	return r.ApiService.QueryMenuByNameExecute(r)
}

/*
QueryMenuByName Method for QueryMenuByName

Gets menu by name.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param name Menu name
 @return ApiQueryMenuByNameRequest
*/
func (a *MenuV1alpha1PublicAPIService) QueryMenuByName(ctx context.Context, name string) ApiQueryMenuByNameRequest {
	return ApiQueryMenuByNameRequest{
		ApiService: a,
		ctx: ctx,
		name: name,
	}
}

// Execute executes the request
//  @return MenuVo
func (a *MenuV1alpha1PublicAPIService) QueryMenuByNameExecute(r ApiQueryMenuByNameRequest) (*MenuVo, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *MenuVo
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "MenuV1alpha1PublicAPIService.QueryMenuByName")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/apis/api.halo.run/v1alpha1/menus/{name}"
	localVarPath = strings.Replace(localVarPath, "{"+"name"+"}", url.PathEscape(parameterValueToString(r.name, "name")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v MenuVo
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiQueryPrimaryMenuRequest struct {
	ctx context.Context
	ApiService MenuV1alpha1PublicAPI
}

func (r ApiQueryPrimaryMenuRequest) Execute() (*MenuVo, *http.Response, error) {
	return r.ApiService.QueryPrimaryMenuExecute(r)
}

/*
QueryPrimaryMenu Method for QueryPrimaryMenu

Gets primary menu.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiQueryPrimaryMenuRequest
*/
func (a *MenuV1alpha1PublicAPIService) QueryPrimaryMenu(ctx context.Context) ApiQueryPrimaryMenuRequest {
	return ApiQueryPrimaryMenuRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return MenuVo
func (a *MenuV1alpha1PublicAPIService) QueryPrimaryMenuExecute(r ApiQueryPrimaryMenuRequest) (*MenuVo, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *MenuVo
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "MenuV1alpha1PublicAPIService.QueryPrimaryMenu")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/apis/api.halo.run/v1alpha1/menus/-"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v MenuVo
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
