/*
Halo

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.20.18
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package public_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SinglePageVo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SinglePageVo{}

// SinglePageVo struct for SinglePageVo
type SinglePageVo struct {
	Content *ContentVo `json:"content,omitempty"`
	Contributors []ContributorVo `json:"contributors,omitempty"`
	Metadata Metadata `json:"metadata"`
	Owner *ContributorVo `json:"owner,omitempty"`
	Spec *SinglePageSpec `json:"spec,omitempty"`
	Stats *StatsVo `json:"stats,omitempty"`
	Status *SinglePageStatus `json:"status,omitempty"`
}

type _SinglePageVo SinglePageVo

// NewSinglePageVo instantiates a new SinglePageVo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSinglePageVo(metadata Metadata) *SinglePageVo {
	this := SinglePageVo{}
	this.Metadata = metadata
	return &this
}

// NewSinglePageVoWithDefaults instantiates a new SinglePageVo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSinglePageVoWithDefaults() *SinglePageVo {
	this := SinglePageVo{}
	return &this
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *SinglePageVo) GetContent() ContentVo {
	if o == nil || IsNil(o.Content) {
		var ret ContentVo
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SinglePageVo) GetContentOk() (*ContentVo, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *SinglePageVo) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given ContentVo and assigns it to the Content field.
func (o *SinglePageVo) SetContent(v ContentVo) {
	o.Content = &v
}

// GetContributors returns the Contributors field value if set, zero value otherwise.
func (o *SinglePageVo) GetContributors() []ContributorVo {
	if o == nil || IsNil(o.Contributors) {
		var ret []ContributorVo
		return ret
	}
	return o.Contributors
}

// GetContributorsOk returns a tuple with the Contributors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SinglePageVo) GetContributorsOk() ([]ContributorVo, bool) {
	if o == nil || IsNil(o.Contributors) {
		return nil, false
	}
	return o.Contributors, true
}

// HasContributors returns a boolean if a field has been set.
func (o *SinglePageVo) HasContributors() bool {
	if o != nil && !IsNil(o.Contributors) {
		return true
	}

	return false
}

// SetContributors gets a reference to the given []ContributorVo and assigns it to the Contributors field.
func (o *SinglePageVo) SetContributors(v []ContributorVo) {
	o.Contributors = v
}

// GetMetadata returns the Metadata field value
func (o *SinglePageVo) GetMetadata() Metadata {
	if o == nil {
		var ret Metadata
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *SinglePageVo) GetMetadataOk() (*Metadata, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metadata, true
}

// SetMetadata sets field value
func (o *SinglePageVo) SetMetadata(v Metadata) {
	o.Metadata = v
}

// GetOwner returns the Owner field value if set, zero value otherwise.
func (o *SinglePageVo) GetOwner() ContributorVo {
	if o == nil || IsNil(o.Owner) {
		var ret ContributorVo
		return ret
	}
	return *o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SinglePageVo) GetOwnerOk() (*ContributorVo, bool) {
	if o == nil || IsNil(o.Owner) {
		return nil, false
	}
	return o.Owner, true
}

// HasOwner returns a boolean if a field has been set.
func (o *SinglePageVo) HasOwner() bool {
	if o != nil && !IsNil(o.Owner) {
		return true
	}

	return false
}

// SetOwner gets a reference to the given ContributorVo and assigns it to the Owner field.
func (o *SinglePageVo) SetOwner(v ContributorVo) {
	o.Owner = &v
}

// GetSpec returns the Spec field value if set, zero value otherwise.
func (o *SinglePageVo) GetSpec() SinglePageSpec {
	if o == nil || IsNil(o.Spec) {
		var ret SinglePageSpec
		return ret
	}
	return *o.Spec
}

// GetSpecOk returns a tuple with the Spec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SinglePageVo) GetSpecOk() (*SinglePageSpec, bool) {
	if o == nil || IsNil(o.Spec) {
		return nil, false
	}
	return o.Spec, true
}

// HasSpec returns a boolean if a field has been set.
func (o *SinglePageVo) HasSpec() bool {
	if o != nil && !IsNil(o.Spec) {
		return true
	}

	return false
}

// SetSpec gets a reference to the given SinglePageSpec and assigns it to the Spec field.
func (o *SinglePageVo) SetSpec(v SinglePageSpec) {
	o.Spec = &v
}

// GetStats returns the Stats field value if set, zero value otherwise.
func (o *SinglePageVo) GetStats() StatsVo {
	if o == nil || IsNil(o.Stats) {
		var ret StatsVo
		return ret
	}
	return *o.Stats
}

// GetStatsOk returns a tuple with the Stats field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SinglePageVo) GetStatsOk() (*StatsVo, bool) {
	if o == nil || IsNil(o.Stats) {
		return nil, false
	}
	return o.Stats, true
}

// HasStats returns a boolean if a field has been set.
func (o *SinglePageVo) HasStats() bool {
	if o != nil && !IsNil(o.Stats) {
		return true
	}

	return false
}

// SetStats gets a reference to the given StatsVo and assigns it to the Stats field.
func (o *SinglePageVo) SetStats(v StatsVo) {
	o.Stats = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *SinglePageVo) GetStatus() SinglePageStatus {
	if o == nil || IsNil(o.Status) {
		var ret SinglePageStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SinglePageVo) GetStatusOk() (*SinglePageStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *SinglePageVo) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given SinglePageStatus and assigns it to the Status field.
func (o *SinglePageVo) SetStatus(v SinglePageStatus) {
	o.Status = &v
}

func (o SinglePageVo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SinglePageVo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	if !IsNil(o.Contributors) {
		toSerialize["contributors"] = o.Contributors
	}
	toSerialize["metadata"] = o.Metadata
	if !IsNil(o.Owner) {
		toSerialize["owner"] = o.Owner
	}
	if !IsNil(o.Spec) {
		toSerialize["spec"] = o.Spec
	}
	if !IsNil(o.Stats) {
		toSerialize["stats"] = o.Stats
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

func (o *SinglePageVo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"metadata",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSinglePageVo := _SinglePageVo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSinglePageVo)

	if err != nil {
		return err
	}

	*o = SinglePageVo(varSinglePageVo)

	return err
}

type NullableSinglePageVo struct {
	value *SinglePageVo
	isSet bool
}

func (v NullableSinglePageVo) Get() *SinglePageVo {
	return v.value
}

func (v *NullableSinglePageVo) Set(val *SinglePageVo) {
	v.value = val
	v.isSet = true
}

func (v NullableSinglePageVo) IsSet() bool {
	return v.isSet
}

func (v *NullableSinglePageVo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSinglePageVo(val *SinglePageVo) *NullableSinglePageVo {
	return &NullableSinglePageVo{value: val, isSet: true}
}

func (v NullableSinglePageVo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSinglePageVo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


